# Generated by Django 2.2.24 on 2021-11-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. Between 6 to 20 characters. Letters, digits and @/./+/-/_ only.', max_length=20, unique=True, verbose_name='username'),
        ),
    ]
